# -*- coding: utf-8 -*-
"""FINALE_DLT_ROBOTICA_PROGETTINO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KiNN4MvfmlMcO9lodXqJt2wOIQyHYMi

## **Computer and Robot Vision**
---
---

Università degli Studi Milano Bicocca \
CdLM Informatica — A.A 2025/2026

---
---

Nome/Cognome: Oleksandra Golub \
Matricola: 856706

#### **Librerie + parametri globali**
"""

# caricamento delle librerie
import os
import numpy as np
import matplotlib.pyplot as plt
import cv2
from google.colab import drive

# riproducibilità + settaggi RANSAC
SEED = 0           # seed fisso per garantire riproducibilità
BEST_THR = 10.0    # soglia di inlier selezionata dopo analisi sperimentale
N_ITERS = 5000     # numero di iterazioni RANSAC

"""#### **Caricamento immagini**"""

# montaggio Google Drive
drive.mount('/content/drive')

# percorso base del dataset
BASE = "/content/drive/MyDrive/lab_robot_and_computer_vision/casa/"
BASE_LAB = "/content/drive/MyDrive/lab_robot_and_computer_vision/lab/"

# percorso dell'immagine analizzata
img1_path = os.path.join(BASE, "tel_ale2.jpeg")
img2_path = os.path.join(BASE, "tel_mmm7.jpeg")
img3_path = os.path.join(BASE, "tab_ale2.jpeg")
img1_lab_path = os.path.join(BASE_LAB, "IMG_1234.JPG")
img2_lab_path = os.path.join(BASE_LAB, "IMG_1235.JPG")
img3_lab_path = os.path.join(BASE_LAB, 'IMG_1237.png')
img4_lab_path = os.path.join(BASE_LAB, "IMG_1238.png")

# lettura immagine in formato BGR (OpenCV)
img1_bgr = cv2.imread(img1_path)
img2_bgr = cv2.imread(img2_path)
img3_bgr = cv2.imread(img3_path)
img1_lab_bgr = cv2.imread(img1_lab_path)
img2_lab_bgr = cv2.imread(img2_lab_path)
img3_lab_bgr = cv2.imread(img3_lab_path)
img4_lab_bgr = cv2.imread(img4_lab_path)


paths = [
    img1_path, img2_path, img3_path,
    img1_lab_path, img2_lab_path, img3_lab_path, img4_lab_path
]

# verifica esistenza file
for p in paths:
    print(os.path.basename(p), "->", os.path.exists(p))

# conversione da BGR a RGB per visualizzazione corretta con matplotlib
img1 = cv2.cvtColor(img1_bgr, cv2.COLOR_BGR2RGB)
img2 = cv2.cvtColor(img2_bgr, cv2.COLOR_BGR2RGB)
img3 = cv2.cvtColor(img3_bgr, cv2.COLOR_BGR2RGB)
img1_lab = cv2.cvtColor(img1_lab_bgr, cv2.COLOR_BGR2RGB)
img2_lab = cv2.cvtColor(img2_lab_bgr, cv2.COLOR_BGR2RGB)
img3_lab = cv2.cvtColor(img3_lab_bgr, cv2.COLOR_BGR2RGB)
img4_lab = cv2.cvtColor(img4_lab_bgr, cv2.COLOR_BGR2RGB)

print("tel_ale2 shape:", img1.shape)
print("tel_mmm7 shape:", img2.shape)
print("tab_ale2 shape:", img3.shape)
print("IMG_1234 shape:", img1_lab.shape)
print("IMG_1235 shape:", img2_lab.shape)
print("IMG_1237 shape:", img3_lab.shape)
print("IMG_1238 shape:", img4_lab.shape)

"""#### **Dati di input: corrispondenze 3D/2D**"""

# STRUTTURA:
# - per le analisi di 40 punti 3d/2d ho usato 3 immagini fatte a casa
# - per le analisi di 9 punti 3d/2d ho usato 3 immagini fatte in labolatorio


# coordinate 3D dei punti nel sistema di riferimento del mondo reale (misurati con metro)
xyz = np.array([
    [0.0, 0.0, 0.0],   # 1
    [3.5, 2.5, 5.2],   # 2
    [11.1, 3.7, 0.0],   # 3
    [0.0, 0.0, -2.7],   # 4
    [11.1, 3.7, 8.3],   # 5
    [46.7, 2.2, 7.2],   # 6
    [29.2, 7.9, 0.0],   # 7
    [-1.7, 19.1, 0.0],   # 8
    [-2.3, 21.1, 13],   # 9
    [4.3,  37.4, 14.2],   # 10
    [26.7, 36.9, 17.7],   # 11
    [35.9, 10.1, 8.0],   # 12
    [22.9, 21.5, 15],   # 13
    [18.7, 5.6, 0.0],   # 14
    [26.2, 11.3, 4.0],   # 15
    [48.5, 2.4, 7.8],   # 16
    [51.8, 19.6, 6.8],   # 17
    [62.7, 15.1, 6.8],   # 18
    [54.7, 36.8, 17.7],   # 19
    [29.1, 8.1, 4],   # 20
    [54.7, 36.9, 0.0],   # 21
    [71.5, 18.0, 28.0],   # 22
    [86.5, 10.6, 4.0],   # 23
    [87.7, 6.1, 0.0],   # 24
    [97.2, 0.6, 0.0],   # 25
    [100.0, 0.0, 0.0],   # 26
    [100.0, 0.0, -2.7],   # 27
    [97.3, 0.7, 11.8],   # 28
    [100.9, 3.2, 11.9],   # 29
    [82.6, 6.4, 0.0],   # 30
    [91.0, 39.2, 15.5],   # 31
    [97.0, 26.9, 5.4],   # 32
    [95.0, 37.3, 15.5],   # 33
    [93.0, 27.8, 5.6],   # 34
    [95.9, 27.1, 5.6],   # 35
    [83.4, 11.3, 0.0],   # 36
    [18.7, 5.6, 8.3],   # 37
    [4.5, 22.9, 13.0],   # 38
    [26.3, 11.2, 0.0],   # 39
    [52.0, 2.4, 7.8],   # 40
], dtype=float)

# coordinate 2D dei punti selezionati manualmente sull'immagine (su Photoshop)
uv1 = np.array([
    [169, 735],  # 1
    [229, 644],  # 2
	  [379, 701],  # 3
    [178, 774],  # 4
	  [356, 589],  # 5
    [923, 613],  # 6
	  [673, 662],  # 7
	  [273, 592],  # 8
    [231, 420],  # 9
	  [410, 349],  # 10
    [677, 304],  # 11
    [754, 536],  # 12
	  [592, 386],  # 13
    [515, 683],  # 14
	  [631, 592],  # 15
    [955, 601],  # 16
	  [986, 501],  # 17
	  [1161, 535],  # 18
    [1012, 308],  # 19
	  [669, 609],  # 20
    [1008, 504],  # 21
    [1270, 231],  # 22
	  [1465, 595],  # 23
    [1498, 668],  # 24
	  [1677, 709],  # 25
    [1708, 716],  # 26
	  [1698, 752],  # 27
	  [1731, 549],  # 28
    [1756, 534],  # 29
	  [1429, 667],  # 30
    [1406, 328],  # 31
    [1518, 489],  # 32
	  [1469, 337],  # 33
    [1456, 475],  # 34
	  [1498, 478],  # 35
    [1407, 634],  # 36
	  [497, 573],  # 37
	  [347, 409],  # 38
    [635, 642],  # 39
	  [1000, 597],  # 40
], dtype=float)


uv2 = np.array([
    [86, 759],  # 1
    [149, 653],  # 2
	  [314, 698],  # 3
    [102, 799],  # 4
	  [279, 583],  # 5
    [908, 560],  # 6
	  [636, 630],  # 7
	  [190, 582],  # 8
	  [127, 398],  # 9
	  [319, 301],  # 10
    [608, 236],  # 11
    [719, 488],  # 12
	  [526, 335],  # 13
    [461, 666],  # 14
	  [588, 554],  # 15
    [940, 544],  # 16
	  [958, 429],  # 17
	  [1147, 456],  # 18
    [967, 220],  # 19
	  [626, 573],  # 20
    [973, 423],  # 21
    [1243, 132],  # 22
	  [1462, 498],  # 23
    [1499, 570],  # 24
	  [1674, 600],  # 25
    [1713, 607],  # 26
	  [1704, 643],  # 27
	  [1723, 437],  # 28
    [1744, 418],  # 29
	  [1430, 575],  # 30
    [1368, 217],  # 31
    [1493, 376],  # 32
	  [1433, 222],  # 33
    [1431, 366],  # 34
	  [1473, 366],  # 35
    [1402, 540],  # 36
	  [433, 552],  # 37
	  [257, 377],  # 38
    [596, 608],  # 39
	  [993, 539],  # 40
], dtype=float)

uv3 = np.array([
    [217, 606],  # 1
    [258, 540],  # 2
	  [366, 586],  # 3
    [224, 635],  # 4
	  [348, 500],  # 5
    [767, 526],  # 6
	  [583, 566],  # 7
	  [294, 513],  # 8
    [263, 380],  # 9
	  [396, 333],  # 10
    [597, 294],  # 11
    [643, 467],  # 12
	  [524, 355],  # 13
    [463, 577],  # 14
	  [552, 513],  # 15
    [792, 517],  # 16
	  [832, 449],  # 17
	  [968, 473],  # 18
    [862, 294],  # 19
	  [578, 525],  # 20
    [860, 459],  # 21
    [1058, 219],  # 22
	  [1217, 521],  # 23
    [1243, 581],  # 24
    [1388, 613],  # 25
    [1412, 620],  # 26
	  [1405, 648],  # 27
	  [1432, 477],  # 28
    [1457, 467],  # 29
	  [1185, 579],  # 30
    [1195, 310],  # 31
    [1281, 442],  # 32
	  [1248, 316],  # 33
    [1231, 431],  # 34
	  [1266, 433],  # 35
    [1173, 556],  # 36
	  [448, 491],  # 37
	  [347, 373],  # 38
    [555, 551],  # 39
	  [828, 515],  # 40
], dtype=float)



# coordinate 3D dei punti nel sistema di riferimento del mondo reale in labolatorio
xyz_lab = np.array([
    [0.0,   0.0,    0.0],   # 1
    [0.0,   0.0,   -2.7],   # 2
    [16.4,  15.2,   6.3],   # 3
    [11.5,  44.0,   8.4],   # 4
    [34.2,  29.7,   7.5],   # 5
    [43.5, 104.0,  30.5],   # 6
    [41.1,   4.2,   0.0],   # 7
    [43.5,   2.2, -10.0],   # 8
    [47.0,  24.2,   4.6],   # 9
], dtype=float)

# coordinate 2D dei punti selezionati manualmente sulle immagini prese in labolatorio
uv1_lab = np.array([
    [1450, 3904],  # 1
    [1460, 3996],  # 2
    [2220, 3247],  # 3
    [2111, 2688],  # 4
    [2682, 2799],  # 5
    [2877, 1643],  # 6
    [3208, 3669],  # 7
    [3307, 4093],  # 8
    [3832, 3059],  # 9
], dtype=float)

uv2_lab = np.array([
    [ 434, 3850],  # 1
    [ 463, 3983],  # 2
    [1682, 2965],  # 3
    [1708, 2304],  # 4
    [2415, 2424],  # 5
    [2801, 1162],  # 6
    [3024, 3547],  # 7
    [3169, 4152],  # 8
    [3937, 2755],  # 9
], dtype=float)

uv3_lab = np.array([
    [  65, 1145],  # 1
    [  80, 1214],  # 2
    [ 738,  808],  # 3
    [ 796,  595],  # 4
    [1118,  632],  # 5
    [1357,  177],  # 6
    [1363, 1062],  # 7
    [1431, 1373],  # 8
    [1843,  780],  # 9
], dtype=float)

uv4_lab = np.array([
    [ 323, 1266],  # 1
    [ 336, 1305],  # 2
    [ 752,  954],  # 3
    [ 778,  660],  # 4
    [1036,  732],  # 5
    [1254,  120],  # 6
    [1207, 1189],  # 7
    [1254, 1379],  # 8
    [1593,  885],  # 9
], dtype=float)

"""#### **Normalizzazione di Hartley (stabilità numerica per DLT)**"""

# la normalizzazione di Hartley migliora il condizionamento numerico del DLT
# centrando i punti nell’origine e scalando la distanza media a √2 (in caso di 2D) o √3 (in caso di 3D),
# rendendo la stima tramite SVD più stabile

# normalizzazione di Hartley per punti 2D
def hartley_normalize_2d(uv):
    uv = np.asarray(uv, float)                     # converte le coordinate 2D in array NumPy di tipo float
    c = uv.mean(axis=0)                            # calcolo baricentro
    uv0 = uv - c                                   # traslazione: da centro a origine
    d = np.sqrt((uv0**2).sum(axis=1))              # distanza di ogni punto dall'origine
    s = np.sqrt(2) / (d.mean() + 1e-12)            # fattore di scala per avere distanza media = sqrt(2)
    T = np.array([[s, 0, -s*c[0]],                 # matrice omogenea di trasformazione (scala + traslazione)
                  [0, s, -s*c[1]],
                  [0, 0, 1]], dtype=float)

    uv_h = np.c_[uv, np.ones(len(uv))].T           # applicazione trasformazione
    uvn_h = T @ uv_h

    uvn = (uvn_h[:2] / (uvn_h[2:3] + 1e-12)).T     # ritorno a coordinate cartesiane
    return T, uvn                                  # T è la matrice 3x3 di normalizzazione, uvn sono i punti normalizzati

# normalizzazione di Hartley per punti 3D
def hartley_normalize_3d(xyz):
    xyz = np.asarray(xyz, float)                    # converte le coordinate 3D in array NumPy di tipo float
    c = xyz.mean(axis=0)                            # calcolo baricentro
    x0 = xyz - c                                    # traslazione: da centro a origine
    d = np.sqrt((x0**2).sum(axis=1))                # distanza di ogni punto dall'origine
    s = np.sqrt(3) / (d.mean() + 1e-12)             # fattore di scala per avere distanza media = sqrt(3)
    T = np.array([[s, 0, 0, -s*c[0]],               # matrice omogenea di trasformazione (scala + traslazione)
                  [0, s, 0, -s*c[1]],
                  [0, 0, s, -s*c[2]],
                  [0, 0, 0, 1]], dtype=float)

    X_h = np.c_[xyz, np.ones(len(xyz))].T           # applicazione trasformazione
    Xn_h = T @ X_h

    Xn = (Xn_h[:3] / (Xn_h[3:4] + 1e-12)).T         # ritorno a coordinate cartesiane
    return T, Xn                                    # T è la matrice 4x4 di normalizzazione, Xn sono i punti normalizzati

"""#### **Direct Linear Transform: stima della matrice di proiezione P da corrispondenze 3D/2D**"""

# stima della matrice di proiezione P (3x4) tramite DLT a partire da corrispondenze 3D/2D
def dlt_P_from_correspondences(xyz, uv):
    xyz = np.asarray(xyz, float)      # Nx3 punti 3D nel mondo
    uv  = np.asarray(uv, float)       # Nx2 punti 2D nell'immagine

    n = xyz.shape[0]
    if n < 6:
        # P ha 12 parametri ma è definita a scala, quindi 11 gradi di libertà
        # ogni punto dà 2 equazioni (x,y), quindi servono almeno 6 punti
        raise ValueError("DLT richiede almeno 6 punti (11 gradi di libertà)!")

    # normalizzazione di Hartley
    T3, Xn = hartley_normalize_3d(xyz)   # punti 3D normalizzati + trasformazione T3
    T2, xn = hartley_normalize_2d(uv)    # punti 2D normalizzati + trasformazione T2

    # parte della costruzione della matrice A
    # ogni corrispondenza fornisce 2 equazioni lineari (una per x e una per y)
    # quindi A ha dimensione (2n x 12)
    A = []
    for i in range(n):
        X, Y, Z = Xn[i]  # punto 3D normalizzato
        x, y    = xn[i]  # punto 2D normalizzato

        # prima equazione (coordinata x)
        A.append([X, Y, Z, 1,
                  0, 0, 0, 0,
                  -x*X, -x*Y, -x*Z, -x])

        # seconda equazione (coordinata y)
        A.append([0, 0, 0, 0,
                  X, Y, Z, 1,
                  -y*X, -y*Y, -y*Z, -y])

    A = np.asarray(A, float)

    # risoluzione del sistema Ap = 0 tramite SVD
    _, _, Vt = np.linalg.svd(A)    # SVD della matrice A (avviene la decomposizione ai valori singolari di A)

    # matrice di proiezione stimata nello spazio normalizzato
    Pn = Vt[-1].reshape(3, 4)      # si prende l’ultima riga di Vt e lo si rimodella in matrice 3×4

    # la soluzione è il vettore singolare associato al valore singolare minimo (ultima riga di Vt equivalente all’ultima colonna di V)

    # denormalizzazione: ritorno al sistema originale
    P = np.linalg.inv(T2) @ Pn @ T3
    # dove @ T3 riporta i punti 3D dal sistema normalizzato a quello reale
    # e inv(T2) @ riporta i punti immagine dal sistema normalizzato ai pixel reali

    # fissaggio della scala (la matrice P è definita a fattore moltiplicativo arbitrario)
    if abs(P[-1, -1]) > 1e-12:
        # se P è soluzione, anche λP è soluzione
        # per renderla unica, si impone una convenzione: cioè si divide tutta la matrice per l’ultimo elemento
        P = P / P[-1, -1]
    else:
        # se l’ultimo elemento fosse quasi zero, allora non si può dividere per quello
        # quindi si normalizza usando la norma della matrice
        P = P / (np.linalg.norm(P) + 1e-12)

    return P     # si restituisce la matrice di proiezione finale nel sistema originale

"""#### **Decomposizione P in (K, R, X0) usando QR**"""

# P = K [R ∣ −RX0​]
# K : matrice intrinseca (focale, centro ottico, skew)
# R : matrice di rotazione (orientamento camera)
# X0 : centro della camera nel mondo

def decompose_P_QR(P):
    P = np.asarray(P, float)  # assicura che P sia un array NumPy in formato float

    # separazione P = [H3 | h]
    H3 = P[:, :3]    # estrazione della parte 3×3
    h  = P[:, 3]     # estrazione dell'ultima colonna

    # calcolo del centro camera (è il punto 3D che viene proiettato all’infinito)
    # geometricamente è la posizione della camera nel sistema mondo
    X0 = -np.linalg.inv(H3) @ h

    # si applica la fattorizzazione QR all’inversa di H3 perché la matrice 3×3 della proiezione può essere vista come prodotto tra matrice intrinseca K e rotazione R
    H3_inv = np.linalg.inv(H3)
    # lavorando su H3_inv, la QR consente di separare in modo stabile la componente di rotazione (ortogonale) da quella intrinseca (triangolare superiore)
    Q, R_upper = np.linalg.qr(H3_inv)

    # estrazione R e K
    R = Q.T                        # si ottiene R ortogonale
    K = np.linalg.inv(R_upper)     # si ottiene K triangolare superiore

    # normalizzazione di K: impone K[2,2] = 1
    K = K / (K[2,2] + 1e-12)

    # forza fx, fy positivi in modo deterministico
    for j in [0, 1]:
        if K[j, j] < 0:        # se le focali risultano negative
            K[:, j] *= -1      # si inverte il segno della colonna di K
            R[j, :] *= -1      # si inverte la riga corrispondente di R

    # una rotazione valida deve avere det(R)=+1, con il -1 si ha una riflessione e bisogna correggere invertendo segno
    if np.linalg.det(R) < 0:
        K[:, 0] *= -1
        R[0, :] *= -1

    return K, R, X0    # restituisce matrice intrinseca, rotazione e centro della camera

"""#### **Proiezione + errori di riproiezione + visualizzazione**"""

# proiettare punti 3D nel piano immagine usando la matrice P
def project_points(P, xyz):
    X = np.c_[xyz, np.ones(len(xyz))]        # aggiunge coordinata omogenea (X,Y,Z) -> (X,Y,Z,1)
    x = (P @ X.T).T                          # proiezione in coordinate omogenee: x = PX

    # normalizzazione omogenea: divide per la terza coordinata (w)
    # per tornare a coordinate cartesiane (u, v)
    x = x / (x[:, [2]] + 1e-12)              # conversione da coordinate omogenee a cartesiane

    return x[:, :2]                          # restituisce solo coordinate 2D (u,v)

# calcolo errore di riproiezione per ogni punto
def reprojection_errors(P, xyz, uv):
    uv_hat = project_points(P, xyz)          # punti riproiettati
    e = np.linalg.norm(uv_hat - uv, axis=1)  # distanza euclidea in pixel
    return e, uv_hat

# calcolo errore RMSE (media degli errori quadratici) globale
def reprojection_rmse(P, xyz, uv):
    e, _ = reprojection_errors(P, xyz, uv)
    return float(np.sqrt((e**2).mean())), project_points(P, xyz)

# overlay osservati vs riproiettati
def overlay(img, uv_obs_all, uv_hat_all, title, mask=None, color_text="red"):
    uv_obs_all = np.asarray(uv_obs_all, float)
    uv_hat_all = np.asarray(uv_hat_all, float)
    n = len(uv_obs_all)

     # se non fornita, usa tutti i punti
    if mask is None:
        mask = np.ones(n, dtype=bool)
    else:
        mask = np.asarray(mask, dtype=bool)

    plt.figure(figsize=(18, 10), dpi=120)
    plt.imshow(img)

    # punti filtrati
    uv_obs = uv_obs_all[mask]
    uv_hat = uv_hat_all[mask]

    # disegno punti osservati e riproiettati
    plt.scatter(uv_obs[:, 0], uv_obs[:, 1], s=80, marker='o', label='observed')
    plt.scatter(uv_hat[:, 0], uv_hat[:, 1], s=80, marker='x', label='reprojected')

    # mantiene ID originali
    idxs = np.where(mask)[0]
    for i in idxs:
        p = uv_obs_all[i]
        q = uv_hat_all[i]
        plt.plot([p[0], q[0]], [p[1], q[1]], linewidth=1)
        plt.text(p[0] + 10, p[1] + 10, str(i + 1), fontsize=14, color=color_text)

    plt.title(title)
    plt.axis("off")
    plt.legend()
    plt.show()

# visualizzazione solo outlier con errore numerico
def overlay_outliers_with_error(img, uv_obs, uv_hat, errors, inliers, thr):
    plt.figure(figsize=(18,10), dpi=120)
    plt.imshow(img)

    for i, (p, q, e, ok) in enumerate(zip(uv_obs, uv_hat, errors, inliers), start=1):
        if not ok:   # solo outlier
            plt.scatter(p[0], p[1], color="red", s=150)
            plt.plot([p[0], q[0]], [p[1], q[1]], color="red", linewidth=2)
            plt.text(p[0]+10, p[1]+10, f"{i}:{e:.1f}",
                     color="red", fontsize=14)

    plt.title("Outlier (errore > soglia)")
    plt.axis("off")
    plt.show()

"""#### **RANSAC-DLT: stima robusta della matrice di proiezione P con outlier rejection**"""

# questa funzione combina:
# - DLT per stimare P
# - RANSAC per eliminare outlier (corrispondenze errate)

def dlt_ransac(
    xyz, uv,
    sample_size=6,               # numero minimo di corrispondenze per stimare P (DLT richiede >= 6 punti)
    n_iters=2000,                # numero di iterazioni RANSAC
    thr_px=5.0,                  # soglia errore di riproiezione (in pixel) per definire un inlier
    min_inliers=6,               # numero minimo di inlier per accettare un modello
    seed=0,                      # seed per riproducibilità
    prefer_more_inliers=True     # criterio di selezione del miglior modello
):
    xyz = np.asarray(xyz, float)
    uv  = np.asarray(uv, float)
    n = len(xyz)

    # verifica numero minimo di punti
    if n < sample_size:
        raise ValueError(f"Servono almeno {sample_size} punti, ne hai {n}.")

    rng = np.random.default_rng(seed)           # generatore casuale riproducibile
    best = None                                 # miglior modello trovato
    best_inliers = None                         # maschera dei migliori inlier

    # ciclo principale RANSAC
    for _ in range(n_iters):
        # selezione casuale di un sottoinsieme minimo
        idx = rng.choice(n, size=sample_size, replace=False)

        try:
            # stima di P tramite DLT sui punti campionati
            P = dlt_P_from_correspondences(xyz[idx], uv[idx])
        except Exception:
            # salta iterazione se il sistema è mal condizionato
            continue

        # calcolo errore di riproiezione su tutti i punti
        e, _ = reprojection_errors(P, xyz, uv)

        # classificazione inlier/outlier
        inliers = e < thr_px
        nin = int(inliers.sum())

        # scarta modello se troppo pochi inlier
        if nin < min_inliers:
            continue

        # calcolo RMSE solo sugli inlier
        rmse_in, _ = reprojection_rmse(P, xyz[inliers], uv[inliers])

        # selezione del miglior modello
        if best is None:
            best = {"P": P, "rmse_in": rmse_in, "nin": nin}
            best_inliers = inliers
        else:
            better = False

            # criterio 1: massimizza numero di inlier
            # criterio 2: minimizza RMSE
            if prefer_more_inliers:
                if nin > best["nin"]:
                    better = True
                elif nin == best["nin"] and rmse_in < best["rmse_in"]:
                    better = True
            else:
                # criterio alternativo: solo minimo errore
                if rmse_in < best["rmse_in"]:
                    better = True

            if better:
                best = {"P": P, "rmse_in": rmse_in, "nin": nin}
                best_inliers = inliers

    # se nessun modello valido trovato
    if best is None:
        raise RuntimeError("RANSAC non ha trovato un modello valido. Aumenta n_iters o thr_px.")

    # rifitting finale: ricalcolo P usando tutti gli inlier migliori
    P_refit = dlt_P_from_correspondences(xyz[best_inliers], uv[best_inliers])

    # errore finale sugli inlier
    rmse_refit, uv_hat_in = reprojection_rmse(P_refit, xyz[best_inliers], uv[best_inliers])

    # restituisce modello robusto finale
    return {
        "P": P_refit,                              # matrice di proiezione stimata
        "inliers": best_inliers,                   # maschera inlier
        "nin": int(best_inliers.sum()),            # numero inlier
        "rmse_inliers": float(rmse_refit),         # errore finale
        "uv_hat_in": uv_hat_in                     # punti riproiettati (inlier)
    }

"""#### **Esperimento A: sweep su soglia thr_px**"""

# normalizza la scala di P (P è definita a meno di un fattore moltiplicativo)
def normalize_P_scale(P):
    P = np.asarray(P, float).copy()
    if abs(P[2,3]) > 1e-12:
        P /= P[2,3]                            # se possibile impone P[2,3] = 1
    else:
        P /= (np.linalg.norm(P) + 1e-12)       # fallback se P[2,3] circa 0, si normalizza con la norma di Frobenius
    return P



# distanza tra due matrici tramite norma di Frobenius: ||A - B||_F
# utile per confrontare quanto cambia P, K, R rispetto a un riferimento
def frob(A, B):
    return float(np.linalg.norm(A - B, ord='fro'))



# sweep di RANSAC al variare della soglia thr_px:
# - per ogni soglia stima P con RANSAC-DLT
# - calcola metriche (inlier, RMSE inlier, RMSE globale)
# - decompone P -> (K, R, X0) per controllare consistenza intrinseci/rotazione
# - confronta stabilità di P,K,R rispetto a una soglia di riferimento
def ransac_sweep_thresholds(name, xyz, uv, thresholds=(2,5,10,15,20), iters=5000, seed=0):
    results, Ps, Ks, Rs = [], [], [], []

    # si esegue RANSAC per ciascuna soglia + si salvano le metriche e parametri camera
    for thr in thresholds:
        res = dlt_ransac(xyz, uv, n_iters=iters, thr_px=float(thr), seed=seed)
        P = res["P"]
        inl = res["inliers"]

        # RMSE su tutti i punti (misura quanto P spiega l'intero set, inclusi outlier)
        rmse_all, _ = reprojection_rmse(P, xyz, uv)
        # RMSE sugli inlier (misura qualità del modello sui punti ritenuti inlier)
        rmse_in = res["rmse_inliers"]

        nin = int(inl.sum())
        n = len(xyz)

        # decomposizione P in (K, R, X0) per analizzare parametri intrinseci e orientamento
        K, R, _ = decompose_P_QR(P)

        # si salvano le metriche per questa soglia
        results.append({
            "thr_px": float(thr),
            "inliers": nin,
            "inlier_%": 100.0 * nin / n,
            "rmse_inliers_px": float(rmse_in),
            "rmse_all_px": float(rmse_all),
            "detR": float(np.linalg.det(R)),   # una rotazione valida dovrebbe avere det(R) circa +1
        })

        # vengono salvate le versioni normalizzate per confronti "stabilità" (P è a scala arbitraria)
        Ps.append(normalize_P_scale(P))
        Ks.append(K / (K[2,2] + 1e-12))  # normalizza K imponendo K[2,2]=1 (scala intrinseci)
        Rs.append(R)


    # si sceglie una soglia di riferimento (di default 10 px)
    # e misura quanto le matrici cambiano rispetto a quel riferimento
    ref_idx = thresholds.index(10) if 10 in thresholds else 0
    P_ref, K_ref, R_ref = Ps[ref_idx], Ks[ref_idx], Rs[ref_idx]

    # aggiunge per ogni soglia le distanze Frobenius da P/K/R di riferimento
    for i in range(len(results)):
        results[i]["dP_to_ref_frob"] = frob(Ps[i], P_ref)
        results[i]["dK_to_ref_frob"] = frob(Ks[i], K_ref)
        results[i]["dR_to_ref_frob"] = frob(Rs[i], R_ref)

    # si stampa la tabella riassuntiva
    print("\n" + "="*80)
    print(f"{name} — RANSAC sweep su thr_px (iters={iters}, seed={seed})")
    print("Ref per stabilità: thr_px =", thresholds[ref_idx])
    print("="*80)
    header = f"{'thr':>5} | {'inl':>4} | {'%inl':>6} | {'RMSE_in':>8} | {'RMSE_all':>9} | {'dP':>8} | {'dK':>8} | {'dR':>8}"
    print(header)
    print("-"*len(header))
    for r in results:
        print(f"{r['thr_px']:5.1f} | {r['inliers']:4d} | {r['inlier_%']:6.1f} | "
              f"{r['rmse_inliers_px']:8.2f} | {r['rmse_all_px']:9.2f} | "
              f"{r['dP_to_ref_frob']:8.2f} | {r['dK_to_ref_frob']:8.2f} | {r['dR_to_ref_frob']:8.2f}")

    return results

"""#### **Esperimento B: sweep su numero di punti N**"""

# sweep sul numero di corrispondenze N usate per stimare P (subset),
# ripetendo l’esperimento più volte per ridurre l’effetto del caso
# obiettivo: valutare quanto la stima di P sia stabile/accurata al variare di N
def ransac_sweep_num_points_repeated(
    xyz, uv,
    Ns=(8, 12, 16, 20, 25, 30, 35, 40),      # diversi valori di N (dimensione subset)
    thr_px=10.0,                             # soglia RANSAC (pixel) per definire gli inlier
    iters=5000,                              # iterazioni RANSAC
    base_seed=0,                             # seed base per riproducibilità
    repeats=5                                # ripetizioni per ogni N (stima μ e σ)
):
    xyz = np.asarray(xyz, float)
    uv  = np.asarray(uv,  float)
    n_tot = len(xyz)                         # numero totale di corrispondenze disponibili (es. 40)

    rows = []

    # per ogni valore N: si estraggono i subset casuali e si stima P (con ripetizioni)
    for N in Ns:
        nin_list, pin_list = [], []                    # #inlier e %inlier (rispetto al subset)
        r_in_list = []                                 # RMSE sugli inlier (subset)
        r_subset_list = []                             # RMSE sul subset completo di N punti
        r_40_list = []                                 # RMSE valutato su tutti i 40 punti

        for r in range(repeats):
            # seed diversi: uno per estrarre subset e uno per RANSAC
            # così si separa la casualità del campionamento subset dalla casualità interna a RANSAC
            seed_subset = base_seed + 1000*N + r
            seed_ransac = base_seed + 2000*N + r

            # selezione casuale di un subset di N corrispondenze dal totale
            rng = np.random.default_rng(seed_subset)
            idx = rng.choice(n_tot, size=N, replace=False)

            # stima robusta di P SOLO sui punti del subset
            res = dlt_ransac(
                xyz[idx], uv[idx],
                n_iters=iters,
                thr_px=thr_px,
                seed=seed_ransac
            )

            P = res["P"]
            inl = res["inliers"]      # maschera inlier riferita al subset
            nin = int(inl.sum())      # numero di inlier nel subset

            # metriche di errore
            # - RMSE_subset: quanto P spiega i punti usati per stimarlo (subset)
            # - RMSE_40: quanto P spiega TUTTI i punti (valuta capacità di generalizzare)
            # - RMSE_in: RMSE sugli inlier del subset (qualità sui punti coerenti)
            rmse_subset, _ = reprojection_rmse(P, xyz[idx], uv[idx]) # RMSE calcolato sui punti del subset
            rmse_40, _     = reprojection_rmse(P, xyz, uv)           # RMSE calcolato su tutti i punti (40)
            rmse_in = float(res["rmse_inliers"])                     # inliers del subset

            # salvataggio statistiche della ripetizione r
            nin_list.append(nin)
            pin_list.append(100.0 * nin / N)          # percentuale inlier rispetto al subset
            r_in_list.append(rmse_in)
            r_subset_list.append(float(rmse_subset))
            r_40_list.append(float(rmse_40))

        # aggregazione: media e deviazione standard (stabilità) per questo N
        rows.append({
            "N": int(N),

            "nin_mean": float(np.mean(nin_list)),
            "nin_std":  float(np.std(nin_list, ddof=1)) if repeats > 1 else 0.0,

            "inlier%_mean": float(np.mean(pin_list)),
            "inlier%_std":  float(np.std(pin_list, ddof=1)) if repeats > 1 else 0.0,

            "rmse_in_mean": float(np.mean(r_in_list)),
            "rmse_in_std":  float(np.std(r_in_list, ddof=1)) if repeats > 1 else 0.0,

            "rmse_subset_mean": float(np.mean(r_subset_list)),
            "rmse_subset_std":  float(np.std(r_subset_list, ddof=1)) if repeats > 1 else 0.0,

            "rmse_40_mean": float(np.mean(r_40_list)),
            "rmse_40_std":  float(np.std(r_40_list, ddof=1)) if repeats > 1 else 0.0,
        })

    # stampa della tabella riassuntiva per confrontare l’effetto di N
    print("\n" + "="*95)
    print(f"RANSAC sweep vs #points — {repeats} reps (thr={thr_px}, iters={iters}, base_seed={base_seed})")
    print("="*95)

    print(" N | nin μ±σ | %inl μ±σ | RMSE_in μ±σ | RMSE_sub μ±σ | RMSE_40 μ±σ")
    print("-"*95)

    for r in rows:
        print(
            f"{r['N']:2d} | "
            f"{r['nin_mean']:.1f}±{r['nin_std']:.1f} | "
            f"{r['inlier%_mean']:.1f}±{r['inlier%_std']:.1f} | "
            f"{r['rmse_in_mean']:.2f}±{r['rmse_in_std']:.2f} | "
            f"{r['rmse_subset_mean']:.2f}±{r['rmse_subset_std']:.2f} | "
            f"{r['rmse_40_mean']:.2f}±{r['rmse_40_std']:.2f}"
        )

    return rows

"""#### **Esecuzione esperimenti**"""

# A) sweep sulla soglia di RANSAC (thr_px)

# si analizza come varia la stima della matrice di proiezione P
# al variare della soglia di errore di riproiezione (in pixel)

# L’obiettivo è trovare un buon compromesso tra:
# - numero di inlier
# - errore RMSE
# - stabilità della soluzione (P, K, R)

thresholds = (2, 5, 10, 15, 20)   # diverse soglie in pixel (più bassa = più selettiva)

res_thr = ransac_sweep_thresholds(
    name="tel_ale2.jpeg",        # nome immagine
    xyz=xyz,                     # punti 3D
    uv=uv1,                      # corrispondenze 2D
    thresholds=thresholds,
    iters=N_ITERS,               # numero iterazioni RANSAC
    seed=SEED                    # seed per riproducibilità
)

#res_thr = ransac_sweep_thresholds(
#    name="tel_mmm1.jpeg",        # nome immagine
#    xyz=xyz,                     # punti 3D
#    uv=uv2,                      # corrispondenze 2D
#    thresholds=thresholds,
#    iters=N_ITERS,               # numero iterazioni RANSAC
#    seed=SEED                    # seed per riproducibilità
#)

#res_thr = ransac_sweep_thresholds(
#    name="tab_ale2.jpeg",        # nome immagine
#    xyz=xyz,                     # punti 3D
#    uv=uv3,                      # corrispondenze 2D
#    thresholds=thresholds,
#    iters=N_ITERS,               # numero iterazioni RANSAC
#    seed=SEED                    # seed per riproducibilità
#)

#res_thr = ransac_sweep_thresholds(
#    name="img_lab1.jpeg",        # nome immagine
#    xyz=xyz_lab,                     # punti 3D
#    uv=uv1_lab,                  # corrispondenze 2D
#    thresholds=thresholds,
#    iters=N_ITERS,               # numero iterazioni RANSAC
#    seed=SEED                    # seed per riproducibilità
#)

"""Domanda: Come varia il comportamento di RANSAC al variare della soglia di inlier thr_px?

Parametri:
- thr : threshold, cioè soglia di errore di riproiezione espressa in pixel, ovvero la distanza tra punto osservato (cliccato su Photoshop) e punto riproiettato dal modello P
- inl : numero di punti classificati come inlier sul totale
- %inl : percentuale di punti classificati come inlier sul totale
- RMSE_in : errore medio calcolato solo sugli inlier
- RMSE_all : errore medio calcolato su tutti i 40 punti
- dP, dK, dR : indicatori di stabilità del modello stimato

Piu precisamente:
- dP : differenza tra matrici di proiezione, ovvero dato che P è la matrice 3×4 che mappa i punti 3D in 2D, si calcola la norma di Frobenius della differenza per capire se i due modelli sono tanto diversi oppure no
- dK : differenza parametri intrinseci, ovvero la misura di quanto cambiano i seguenti parametri: focali (fx, fy) e centro ottico (cx, cy) della matrice intrinseca K
- dR : differenza rotazione, ovvero la misura di quanto cambia l’orientamento della camera

Osservazioni:
- thr : se la distanza tra punto osservato e riproiettato è minore di thr, allora il punto è considerato INLIER, altrimenti OUTLIER
- inl e %inl : all’aumentare della soglia, RANSAC accetta più punti come inlier
- RMSE_in : con la soglia piccola, si accettano solo i punti molto coerenti (errore basso), mentre con la soglia grande, si accettano anche punti rumorosi (errore cresce)
- RMSE_all : l’errore globale resta sempre circa 7-9 px, quasi indipendente dalla varianza della soglia
- dP : con thr troppo piccolo, ci sono pochi inlier (soluzione instabile), con thr troppo grande, ci sono anche gli outlier (soluzione si deforma), ma con thr=10 si arriva a un'equilibrio
- dK : è grande soprattutto per thr=5, 15, 20, quindi gli intrinseci sono sensibili agli outlier
- dR : è sempre piccolo (circa 0.01-0.08), quindi la rotazione è relativamente stabile

QUINDI:

- Soglie troppo piccole (2 px) producono pochi inlier e una stima instabile della matrice di proiezione

- Soglie troppo grandi (15-20 px) includono punti rumorosi, aumentando l’errore sugli inlier e alterando soprattutto la stima dei parametri intrinseci

- L’errore globale sui 40 punti rimane quasi costante (circa 7-9 px), indicando che è dominato da pochi outlier molto inconsistenti

- Una soglia intermedia di 10 px rappresenta il miglior compromesso, garantendo:
  - circa l’80% di inlier
  - errore sugli inlier contenuto (circa 5 px)
  - minima variazione della matrice di proiezione (dP = 0)
"""

# B) Run finale con soglia scelta (BEST_THR) + overlay e visualizzazione

# obiettivo:
# - stimare P con RANSAC-DLT usando la soglia selezionata
# - valutare l'errore di riproiezione su tutti i punti (inlier + outlier)
# - visualizzare osservati vs riproiettati (overlay) per verificare qualitativamente il risultato

res_best = dlt_ransac(xyz, uv1, n_iters=N_ITERS, thr_px=BEST_THR, seed=SEED)
#res_best = dlt_ransac(xyz, uv2, n_iters=N_ITERS, thr_px=BEST_THR, seed=SEED)
#res_best = dlt_ransac(xyz, uv3, n_iters=N_ITERS, thr_px=BEST_THR, seed=SEED)
#res_best = dlt_ransac(xyz_lab, uv1_lab, n_iters=N_ITERS, thr_px=BEST_THR, seed=SEED)

P_best = res_best["P"]           # matrice di proiezione finale (rifittata sugli inlier)
inl = res_best["inliers"]        # maschera booleana inlier/outlier (per i punti usati nel run)

# calcolo errori di riproiezione su TUTTI i punti disponibili (40)
# serve per capire come il modello si comporta globalmente, non solo sugli inlier
errors, uv_hat_all = reprojection_errors(P_best, xyz, uv1)
#errors, uv_hat_all = reprojection_errors(P_best, xyz, uv2)
#errors, uv_hat_all = reprojection_errors(P_best, xyz, uv3)
#errors, uv_hat_all = reprojection_errors(P_best, xyz_lab, uv1_lab)

# RMSE globale: sqrt(media(errori^2)) su tutti i punti (include outlier)
rmse_all = float(np.sqrt((errors**2).mean()))

# stampa errore per punto
print("Errore per punto:")
for i, (e, ok) in enumerate(zip(errors, inl), start=1):
    tag = "INLIER" if ok else "OUTLIER"
    print(f"Punto {i:2d}: {e:6.2f} px -> {tag}")

# di nuovo si calcola RMSE e punti riproiettati completi tramite la funzione già definita
rmse_all, uv_hat_all = reprojection_rmse(P_best, xyz, uv1)
#rmse_all, uv_hat_all = reprojection_rmse(P_best, xyz, uv2)
#rmse_all, uv_hat_all = reprojection_rmse(P_best, xyz, uv3)
#rmse_all, uv_hat_all = reprojection_rmse(P_best, xyz_lab, uv1_lab)

# riepilogo del best run:
# - numero inlier
# - RMSE sugli inlier (qualità del modello sui punti coerenti)
# - RMSE globale (qualità complessiva, include outlier)
print("\nBEST RUN")
print(f"thr={BEST_THR}, inliers={inl.sum()}/{len(inl)}, RMSE_in={res_best['rmse_inliers']:.2f}px, RMSE_all={rmse_all:.2f}px")

# tutti i punti
overlay(img1, uv1, uv_hat_all, "RANSAC overlay (all points)", mask=None, color_text="pink")
#overlay(img2, uv2, uv_hat_all, "RANSAC overlay (all points)", mask=None, color_text="pink")
#overlay(img3, uv3, uv_hat_all, "RANSAC overlay (all points)", mask=None, color_text="pink")
#overlay(img1_lab, uv1_lab, uv_hat_all, "RANSAC overlay (all points)", mask=None, color_text="pink")

# solo inlier
overlay(img1, uv1, uv_hat_all, "RANSAC overlay (inliers)", mask=inl, color_text="lime")
#overlay(img2, uv2, uv_hat_all, "RANSAC overlay (inliers)", mask=inl, color_text="lime")
#overlay(img3, uv3, uv_hat_all, "RANSAC overlay (inliers)", mask=inl, color_text="lime")
#overlay(img1_lab, uv1_lab, uv_hat_all, "RANSAC overlay (inliers)", mask=inl, color_text="lime")

# solo outlier
overlay(img1, uv1, uv_hat_all, "RANSAC overlay (outliers)", mask=~inl, color_text="red")
#overlay(img2, uv2, uv_hat_all, "RANSAC overlay (outliers)", mask=~inl, color_text="red")
#overlay(img3, uv3, uv_hat_all, "RANSAC overlay (outliers)", mask=~inl, color_text="red")
#overlay(img1_lab, uv1_lab, uv_hat_all, "RANSAC overlay (outliers)", mask=~inl, color_text="red")

# overlay con errore scritto vicino a ogni punto
overlay_outliers_with_error(img1, uv1, uv_hat_all, errors, inl, BEST_THR)
#overlay_outliers_with_error(img2, uv2, uv_hat_all, errors, inl, BEST_THR)
#overlay_outliers_with_error(img3, uv3, uv_hat_all, errors, inl, BEST_THR)
#overlay_outliers_with_error(img1_lab, uv1_lab, uv_hat_all, errors, inl, BEST_THR)

# C) sweep sul numero di punti N (con 5 ripetizioni per ogni N)

# si analizza come varia la qualità e la stabilità della stima di P
# al variare del numero di corrispondenze utilizzate

# Per ogni N:
# - si estrae un subset casuale di N punti
# - si stima P con RANSAC-DLT
# - si ripete 5 volte per ridurre l'effetto della casualità

# L'obiettivo è valutare:
# - accuratezza (RMSE)
# - numero medio di inlier
# - stabilità (deviazione standard)

Ns = (8, 12, 16, 20, 25, 30, 35, 40)

res_N_rep = ransac_sweep_num_points_repeated(
    xyz, uv1,
    Ns=Ns,
    thr_px=BEST_THR,        # uso la soglia ottimale trovata nello sweep precedente
    iters=N_ITERS,
    base_seed=SEED,
    repeats=5               # ripetizioni per stimare media e variabilità
)

#res_N_rep = ransac_sweep_num_points_repeated(
#    xyz, uv2,
#    Ns=Ns,
#    thr_px=BEST_THR,        # uso la soglia ottimale trovata nello sweep precedente
#    iters=N_ITERS,
#    base_seed=SEED,
#    repeats=5               # ripetizioni per stimare media e variabilità
#)

#res_N_rep = ransac_sweep_num_points_repeated(
#    xyz, uv3,
#    Ns=Ns,
#    thr_px=BEST_THR,        # uso la soglia ottimale trovata nello sweep precedente
#    iters=N_ITERS,
#    base_seed=SEED,
#    repeats=5               # ripetizioni per stimare media e variabilità
#)

"""Domanda: Come si comporta RANSAC quando aumento il numero di punti disponibili?

Parametri:
- nin μ±σ : numero medio di punti del subset coerenti con il modello stimato da RANSAC
- %inl μ±σ : percentuale di inlier nel subset [il complemento (100 - %inl) stima la percentuale di punti problematici]
- RMSE_in μ±σ : rrore medio calcolato SOLO sugli inlier (si stabilizza intorno a 3-5 px, rappresentando l’errore reale sui punti coerenti)
- RMSE_sub μ±σ : errore su TUTTI i punti del subset
- RMSE_40 μ±σ : capacità del modello stimato con N punti di generalizzare sull’intero set di 40 punti

QUINDI:

- Con pochissimi punti (N=8) la stima è altamente instabile, come evidenziato dall’elevata varianza dell’errore globale (RMSE_40 = 37.97 ± 33.39 px)

- Già a partire da N >= 12 la soluzione diventa significativamente più stabile e ripetibile

- Per N >= 16-20 punti l’errore globale converge a circa 4-5 px, con varianza molto ridotta

- Aumentare ulteriormente il numero di punti oltre 20-30 non produce miglioramenti sostanziali, indicando che l’errore residuo è dominato da outlier e imprecisioni di misura, più che dalla quantità di punti disponibili

#### **Conclusioni finali**

Per rendere la stima della matrice di proiezione P più robusta rispetto a errori di misura e possibili corrispondenze errate, è stato utilizzato RANSAC combinato con DLT e normalizzazione di Hartley.
Quest’ultima consiste nel traslare e scalare i punti prima della stima, migliorando il condizionamento numerico del problema e quindi la stabilità della soluzione

Sono state svolte tre tipologie di analisi:

**a) Analisi della soglia di inlier**:

Lo studio al variare della soglia thr ∈ [2, 20] px mostra che:

- All’aumentare della soglia cresce il numero di inlier (da 11 su 40 a 38 su 40)

- L’RMSE sugli inlier aumenta progressivamente (da 0.7 px a circa 7.3 px), poiché vengono accettati anche punti più rumorosi

- L’RMSE globale sui 40 punti rimane invece quasi costante (circa 7-9 px)

- Gli indicatori di stabilità (dP, dK, dR) mostrano che la soluzione più stabile si ottiene per thr = 10 px, dove le variazioni rispetto al modello di riferimento sono minime

- La soglia thr = 10 px rappresenta quindi il miglior compromesso tra:
    - percentuale di inlier (circa 80%)
    - errore contenuto sugli inlier (circa 5 px)
    - stabilità della matrice di proiezione

**b) Analisi del numero di punti disponibili**

Successivamente è stato analizzato il comportamento di RANSAC al variare del numero di punti N ∈ {8, 12, 16, 20, 25, 30, 35, 40}, ripetendo ogni esperimento 5 volte con subset casuali e seed controllato.

I risultati evidenziano che:

- Con pochi punti (N = 8) la stima è altamente instabile
(RMSE_40 = 37.43 ± 32.49)

- Già a partire da N >= 12-16 la soluzione diventa stabile e ripetibile

- Per N >= 20 l’errore globale converge a circa 15-16 px, con varianza molto ridotta

- Aumentare ulteriormente il numero di punti oltre 20-30 non produce miglioramenti significativi

Questo indica che l’errore residuo non è limitato dal numero di punti disponibili, ma è dominato dalla presenza di alcuni outlier consistenti


**c) Analisi puntuale degli errori**

L’analisi per punto mostra che:
- 33 punti risultano coerenti (errori 1-9 px circa)
- 8 punti presentano errori elevati (fino a 27 px), compatibili con mismatch o imprecisioni di annotazione

RANSAC riesce a scartare efficacemente questi punti, mantenendo basso l’errore sugli inlier (circa 4.8 px), mentre l’errore globale resta intorno a 10 px perché include anche tali punti fortemente inconsistenti
"""